### ISSUE TITLE
return not working

### ISSUE THREAD

**Issue by geek2003** [archieroques/flotilla-easy#4]
First of all what a great library.

after the sensors and other inputs were not responding I dove into the code and found that it worked when I changed it to print instead of return

the return works in the shell but not when I run a file.

Is this a problem at my end.

**Comment by archieroques** [comment]
Ok, I think I might know what's gone wrong. 

Just to clarify - what code are you using in your file when it isn't returning?

**Comment by geek2003** [comment]
Import flotilla_easy
flotilla_easy.colour()

Or

flotilla_easy.slider()

**Comment by archieroques** [comment]
Ok: the problem here is that return doesn't do exactly the same thing as print. 

When you type 'flotilla_easy.colour()' that represents a value which colour returns. But at the moment you're not doing anything with it. It's a bit like just typing the number 3 in your code - in the shell it'd give you the number 3 back again like a print, but in a file it'd do nothing. 

So you just need to change your code to 'print(flotilla_easy.colour())'. 

The returns are there because they let you do stuff with the value, and not just print it. So, you could do things like:

var = flotilla_easy.slider() - assigning a variable to a sensor value
Or
flotilla_easy.number(flotilla_easy.slider()) - displaying the sensor value on the number module.

**Comment by geek2003** [comment]
Cheers!    
  
  

  
  
  
  

  
  
>
